export interface Theme {
  id: string;
  name: string;
  description: string;
  /** Preview swatch colors [primary, secondary, accent] */
  preview: [string, string, string];
  /** CSS variable overrides per color-scheme. Omitted vars inherit from the default theme. */
  variables: {
    light?: Record<string, string>;
    dark?: Record<string, string>;
  };
}

export const themes: Theme[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Clean, modern look',
    preview: ['#3b82f6', '#0f172a', '#f8fafc'],
    variables: {},
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep AMOLED black with teal accents',
    preview: ['#2dd4bf', '#000000', '#111111'],
    variables: {
      light: {
        '--color-bg': '#0a0a0a',
        '--color-bg-secondary': '#141414',
        '--color-bg-card': '#111111',
        '--color-bg-hover': '#1a1a1a',
        '--color-text': '#e4e4e7',
        '--color-text-secondary': '#a1a1aa',
        '--color-text-muted': '#71717a',
        '--color-border': '#27272a',
        '--color-border-hover': '#3f3f46',
        '--color-sidebar-bg': '#000000',
        '--color-sidebar-text': '#a1a1aa',
        '--color-sidebar-text-active': '#2dd4bf',
        '--color-sidebar-active-bg': '#111111',
        '--color-sidebar-hover': '#0a0a0a',
        '--color-accent': '#2dd4bf',
        '--color-accent-hover': '#14b8a6',
        '--color-success': '#34d399',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#111111',
        '--color-table-row-hover': '#1a1a1a',
        '--color-table-stripe': '#0d0d0d',
        '--color-slider-track': '#27272a',
        '--color-slider-range': '#2dd4bf',
        '--color-slider-thumb': '#2dd4bf',
      },
      dark: {
        '--color-bg': '#000000',
        '--color-bg-secondary': '#0a0a0a',
        '--color-bg-card': '#0a0a0a',
        '--color-bg-hover': '#141414',
        '--color-text': '#e4e4e7',
        '--color-text-secondary': '#a1a1aa',
        '--color-text-muted': '#71717a',
        '--color-border': '#1c1c1e',
        '--color-border-hover': '#2c2c2e',
        '--color-sidebar-bg': '#000000',
        '--color-sidebar-text': '#a1a1aa',
        '--color-sidebar-text-active': '#2dd4bf',
        '--color-sidebar-active-bg': '#0a0a0a',
        '--color-sidebar-hover': '#050505',
        '--color-accent': '#2dd4bf',
        '--color-accent-hover': '#14b8a6',
        '--color-success': '#34d399',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#0a0a0a',
        '--color-table-row-hover': '#141414',
        '--color-table-stripe': '#050505',
        '--color-slider-track': '#1c1c1e',
        '--color-slider-range': '#2dd4bf',
        '--color-slider-thumb': '#2dd4bf',
      },
    },
  },
  {
    id: 'glass',
    name: 'Glass',
    description: 'Frosted glass with soft purple tones',
    preview: ['#a78bfa', '#1e1b4b', '#312e81'],
    variables: {
      light: {
        '--color-bg': '#f5f3ff',
        '--color-bg-secondary': '#ede9fe',
        '--color-bg-card': 'rgba(255, 255, 255, 0.7)',
        '--color-bg-hover': '#e9e5fb',
        '--color-text': '#1e1b4b',
        '--color-text-secondary': '#4c1d95',
        '--color-text-muted': '#7c3aed',
        '--color-border': 'rgba(167, 139, 250, 0.3)',
        '--color-border-hover': 'rgba(167, 139, 250, 0.5)',
        '--color-sidebar-bg': '#1e1b4b',
        '--color-sidebar-text': '#c4b5fd',
        '--color-sidebar-text-active': '#ffffff',
        '--color-sidebar-active-bg': '#312e81',
        '--color-sidebar-hover': '#312e81',
        '--color-accent': '#7c3aed',
        '--color-accent-hover': '#6d28d9',
        '--color-success': '#34d399',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#ede9fe',
        '--color-table-row-hover': '#e9e5fb',
        '--color-table-stripe': '#f0ecfe',
        '--color-slider-track': '#ddd6fe',
        '--color-slider-range': '#7c3aed',
        '--color-slider-thumb': '#ffffff',
        '--radius': '16px',
        '--radius-sm': '10px',
        '--radius-lg': '20px',
      },
      dark: {
        '--color-bg': '#0f0b2a',
        '--color-bg-secondary': '#1a1545',
        '--color-bg-card': 'rgba(30, 27, 75, 0.6)',
        '--color-bg-hover': '#211c52',
        '--color-text': '#e0e7ff',
        '--color-text-secondary': '#a5b4fc',
        '--color-text-muted': '#6366f1',
        '--color-border': 'rgba(99, 102, 241, 0.25)',
        '--color-border-hover': 'rgba(99, 102, 241, 0.4)',
        '--color-sidebar-bg': '#070420',
        '--color-sidebar-text': '#a5b4fc',
        '--color-sidebar-text-active': '#e0e7ff',
        '--color-sidebar-active-bg': '#1a1545',
        '--color-sidebar-hover': '#0f0b2a',
        '--color-accent': '#818cf8',
        '--color-accent-hover': '#6366f1',
        '--color-success': '#34d399',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#1a1545',
        '--color-table-row-hover': '#211c52',
        '--color-table-stripe': '#120e38',
        '--color-slider-track': '#1a1545',
        '--color-slider-range': '#818cf8',
        '--color-slider-thumb': '#e0e7ff',
        '--radius': '16px',
        '--radius-sm': '10px',
        '--radius-lg': '20px',
      },
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Earthy greens and warm neutrals',
    preview: ['#22c55e', '#14532d', '#fef9c3'],
    variables: {
      light: {
        '--color-bg': '#f7fdf5',
        '--color-bg-secondary': '#ecfccb',
        '--color-bg-card': '#ffffff',
        '--color-bg-hover': '#e8f5e0',
        '--color-text': '#14532d',
        '--color-text-secondary': '#166534',
        '--color-text-muted': '#4ade80',
        '--color-border': '#bbf7d0',
        '--color-border-hover': '#86efac',
        '--color-sidebar-bg': '#14532d',
        '--color-sidebar-text': '#86efac',
        '--color-sidebar-text-active': '#ffffff',
        '--color-sidebar-active-bg': '#166534',
        '--color-sidebar-hover': '#166534',
        '--color-accent': '#16a34a',
        '--color-accent-hover': '#15803d',
        '--color-success': '#22c55e',
        '--color-warning': '#eab308',
        '--color-danger': '#ef4444',
        '--color-table-header': '#ecfccb',
        '--color-table-row-hover': '#e8f5e0',
        '--color-table-stripe': '#f0fdf4',
        '--color-slider-track': '#bbf7d0',
        '--color-slider-range': '#16a34a',
        '--color-slider-thumb': '#ffffff',
      },
      dark: {
        '--color-bg': '#052e16',
        '--color-bg-secondary': '#0a3d1f',
        '--color-bg-card': '#0a3d1f',
        '--color-bg-hover': '#14532d',
        '--color-text': '#dcfce7',
        '--color-text-secondary': '#86efac',
        '--color-text-muted': '#4ade80',
        '--color-border': '#166534',
        '--color-border-hover': '#22863a',
        '--color-sidebar-bg': '#022c22',
        '--color-sidebar-text': '#86efac',
        '--color-sidebar-text-active': '#dcfce7',
        '--color-sidebar-active-bg': '#0a3d1f',
        '--color-sidebar-hover': '#052e16',
        '--color-accent': '#4ade80',
        '--color-accent-hover': '#22c55e',
        '--color-success': '#4ade80',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#0a3d1f',
        '--color-table-row-hover': '#14532d',
        '--color-table-stripe': '#062c17',
        '--color-slider-track': '#166534',
        '--color-slider-range': '#4ade80',
        '--color-slider-thumb': '#dcfce7',
      },
    },
  },
  {
    id: 'rose',
    name: 'Rosé',
    description: 'Soft pinks with warm copper accents',
    preview: ['#f43f5e', '#4c0519', '#fff1f2'],
    variables: {
      light: {
        '--color-bg': '#fff1f2',
        '--color-bg-secondary': '#ffe4e6',
        '--color-bg-card': '#ffffff',
        '--color-bg-hover': '#fecdd3',
        '--color-text': '#4c0519',
        '--color-text-secondary': '#881337',
        '--color-text-muted': '#e11d48',
        '--color-border': '#fecdd3',
        '--color-border-hover': '#fda4af',
        '--color-sidebar-bg': '#4c0519',
        '--color-sidebar-text': '#fda4af',
        '--color-sidebar-text-active': '#ffffff',
        '--color-sidebar-active-bg': '#881337',
        '--color-sidebar-hover': '#881337',
        '--color-accent': '#e11d48',
        '--color-accent-hover': '#be123c',
        '--color-success': '#22c55e',
        '--color-warning': '#f59e0b',
        '--color-danger': '#ef4444',
        '--color-table-header': '#ffe4e6',
        '--color-table-row-hover': '#fecdd3',
        '--color-table-stripe': '#fff5f6',
        '--color-slider-track': '#fecdd3',
        '--color-slider-range': '#e11d48',
        '--color-slider-thumb': '#ffffff',
      },
      dark: {
        '--color-bg': '#1a0008',
        '--color-bg-secondary': '#2a0a14',
        '--color-bg-card': '#2a0a14',
        '--color-bg-hover': '#3b0f1e',
        '--color-text': '#ffe4e6',
        '--color-text-secondary': '#fda4af',
        '--color-text-muted': '#f87171',
        '--color-border': '#4c0519',
        '--color-border-hover': '#6b0724',
        '--color-sidebar-bg': '#0f0004',
        '--color-sidebar-text': '#fda4af',
        '--color-sidebar-text-active': '#ffe4e6',
        '--color-sidebar-active-bg': '#2a0a14',
        '--color-sidebar-hover': '#1a0008',
        '--color-accent': '#fb7185',
        '--color-accent-hover': '#f43f5e',
        '--color-success': '#4ade80',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#2a0a14',
        '--color-table-row-hover': '#3b0f1e',
        '--color-table-stripe': '#200a10',
        '--color-slider-track': '#4c0519',
        '--color-slider-range': '#fb7185',
        '--color-slider-thumb': '#ffe4e6',
      },
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    description: 'Minimal monochrome with sharp edges',
    preview: ['#a1a1aa', '#18181b', '#fafafa'],
    variables: {
      light: {
        '--color-bg': '#fafafa',
        '--color-bg-secondary': '#f4f4f5',
        '--color-bg-card': '#ffffff',
        '--color-bg-hover': '#e4e4e7',
        '--color-text': '#18181b',
        '--color-text-secondary': '#3f3f46',
        '--color-text-muted': '#a1a1aa',
        '--color-border': '#d4d4d8',
        '--color-border-hover': '#a1a1aa',
        '--color-sidebar-bg': '#18181b',
        '--color-sidebar-text': '#a1a1aa',
        '--color-sidebar-text-active': '#fafafa',
        '--color-sidebar-active-bg': '#27272a',
        '--color-sidebar-hover': '#27272a',
        '--color-accent': '#52525b',
        '--color-accent-hover': '#3f3f46',
        '--color-success': '#22c55e',
        '--color-warning': '#f59e0b',
        '--color-danger': '#ef4444',
        '--color-table-header': '#f4f4f5',
        '--color-table-row-hover': '#e4e4e7',
        '--color-table-stripe': '#f8f8f9',
        '--color-slider-track': '#d4d4d8',
        '--color-slider-range': '#52525b',
        '--color-slider-thumb': '#ffffff',
        '--radius': '4px',
        '--radius-sm': '2px',
        '--radius-lg': '6px',
      },
      dark: {
        '--color-bg': '#09090b',
        '--color-bg-secondary': '#18181b',
        '--color-bg-card': '#18181b',
        '--color-bg-hover': '#27272a',
        '--color-text': '#fafafa',
        '--color-text-secondary': '#a1a1aa',
        '--color-text-muted': '#71717a',
        '--color-border': '#27272a',
        '--color-border-hover': '#3f3f46',
        '--color-sidebar-bg': '#09090b',
        '--color-sidebar-text': '#a1a1aa',
        '--color-sidebar-text-active': '#fafafa',
        '--color-sidebar-active-bg': '#18181b',
        '--color-sidebar-hover': '#0f0f11',
        '--color-accent': '#a1a1aa',
        '--color-accent-hover': '#d4d4d8',
        '--color-success': '#4ade80',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#18181b',
        '--color-table-row-hover': '#27272a',
        '--color-table-stripe': '#0f0f11',
        '--color-slider-track': '#27272a',
        '--color-slider-range': '#a1a1aa',
        '--color-slider-thumb': '#fafafa',
        '--radius': '4px',
        '--radius-sm': '2px',
        '--radius-lg': '6px',
      },
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Deep navy blues with bright cyan highlights',
    preview: ['#06b6d4', '#0c1a3a', '#cffafe'],
    variables: {
      light: {
        '--color-bg': '#f0fdfa',
        '--color-bg-secondary': '#ccfbf1',
        '--color-bg-card': '#ffffff',
        '--color-bg-hover': '#c4f4ed',
        '--color-text': '#0c1a3a',
        '--color-text-secondary': '#155e75',
        '--color-text-muted': '#0891b2',
        '--color-border': '#99f6e4',
        '--color-border-hover': '#5eead4',
        '--color-sidebar-bg': '#0c1a3a',
        '--color-sidebar-text': '#67e8f9',
        '--color-sidebar-text-active': '#ffffff',
        '--color-sidebar-active-bg': '#164e63',
        '--color-sidebar-hover': '#164e63',
        '--color-accent': '#0891b2',
        '--color-accent-hover': '#0e7490',
        '--color-success': '#22c55e',
        '--color-warning': '#f59e0b',
        '--color-danger': '#ef4444',
        '--color-table-header': '#ccfbf1',
        '--color-table-row-hover': '#c4f4ed',
        '--color-table-stripe': '#ecfdf5',
        '--color-slider-track': '#99f6e4',
        '--color-slider-range': '#0891b2',
        '--color-slider-thumb': '#ffffff',
      },
      dark: {
        '--color-bg': '#041c32',
        '--color-bg-secondary': '#0a2a47',
        '--color-bg-card': '#0a2a47',
        '--color-bg-hover': '#0e3a5c',
        '--color-text': '#cffafe',
        '--color-text-secondary': '#67e8f9',
        '--color-text-muted': '#22d3ee',
        '--color-border': '#164e63',
        '--color-border-hover': '#1e6a82',
        '--color-sidebar-bg': '#020e1f',
        '--color-sidebar-text': '#67e8f9',
        '--color-sidebar-text-active': '#cffafe',
        '--color-sidebar-active-bg': '#0a2a47',
        '--color-sidebar-hover': '#041c32',
        '--color-accent': '#22d3ee',
        '--color-accent-hover': '#06b6d4',
        '--color-success': '#4ade80',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#0a2a47',
        '--color-table-row-hover': '#0e3a5c',
        '--color-table-stripe': '#062236',
        '--color-slider-track': '#164e63',
        '--color-slider-range': '#22d3ee',
        '--color-slider-thumb': '#cffafe',
      },
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    description: 'Warm golden tones inspired by smart lighting',
    preview: ['#f59e0b', '#451a03', '#fef3c7'],
    variables: {
      light: {
        '--color-bg': '#fffbeb',
        '--color-bg-secondary': '#fef3c7',
        '--color-bg-card': '#ffffff',
        '--color-bg-hover': '#fde68a',
        '--color-text': '#451a03',
        '--color-text-secondary': '#78350f',
        '--color-text-muted': '#b45309',
        '--color-border': '#fde68a',
        '--color-border-hover': '#fcd34d',
        '--color-sidebar-bg': '#451a03',
        '--color-sidebar-text': '#fcd34d',
        '--color-sidebar-text-active': '#ffffff',
        '--color-sidebar-active-bg': '#78350f',
        '--color-sidebar-hover': '#78350f',
        '--color-accent': '#d97706',
        '--color-accent-hover': '#b45309',
        '--color-success': '#22c55e',
        '--color-warning': '#f59e0b',
        '--color-danger': '#ef4444',
        '--color-table-header': '#fef3c7',
        '--color-table-row-hover': '#fde68a',
        '--color-table-stripe': '#fefce8',
        '--color-slider-track': '#fde68a',
        '--color-slider-range': '#d97706',
        '--color-slider-thumb': '#ffffff',
      },
      dark: {
        '--color-bg': '#1a0e00',
        '--color-bg-secondary': '#2a1a06',
        '--color-bg-card': '#2a1a06',
        '--color-bg-hover': '#3b2510',
        '--color-text': '#fef3c7',
        '--color-text-secondary': '#fcd34d',
        '--color-text-muted': '#f59e0b',
        '--color-border': '#451a03',
        '--color-border-hover': '#5c2a08',
        '--color-sidebar-bg': '#0f0800',
        '--color-sidebar-text': '#fcd34d',
        '--color-sidebar-text-active': '#fef3c7',
        '--color-sidebar-active-bg': '#2a1a06',
        '--color-sidebar-hover': '#1a0e00',
        '--color-accent': '#fbbf24',
        '--color-accent-hover': '#f59e0b',
        '--color-success': '#4ade80',
        '--color-warning': '#fbbf24',
        '--color-danger': '#f87171',
        '--color-table-header': '#2a1a06',
        '--color-table-row-hover': '#3b2510',
        '--color-table-stripe': '#201208',
        '--color-slider-track': '#451a03',
        '--color-slider-range': '#fbbf24',
        '--color-slider-thumb': '#fef3c7',
      },
    },
  },
  {
    id: 'lcars',
    name: 'LCARS',
    description: 'Starfleet computer interface',
    preview: ['#ff9900', '#000000', '#cc99cc'],
    variables: {
      light: {
        '--color-bg': '#000000',
        '--color-bg-secondary': '#1a1a2e',
        '--color-bg-card': '#0a0a1a',
        '--color-bg-hover': '#1a1a2e',
        '--color-text': '#ff9900',
        '--color-text-secondary': '#cc99cc',
        '--color-text-muted': '#9977aa',
        '--color-border': '#cc6699',
        '--color-border-hover': '#ff9900',

        '--color-sidebar-bg': '#000000',
        '--color-sidebar-text': '#cc99cc',
        '--color-sidebar-text-active': '#ff9900',
        '--color-sidebar-active-bg': '#1a1a2e',
        '--color-sidebar-hover': '#0a0a1a',

        '--color-accent': '#ff9900',
        '--color-accent-hover': '#ffaa22',
        '--color-success': '#99cc66',
        '--color-warning': '#ff9966',
        '--color-danger': '#cc6666',

        '--color-table-header': '#0a0a1a',
        '--color-table-row-hover': '#1a1a2e',
        '--color-table-stripe': '#050510',

        '--color-slider-track': '#1a1a2e',
        '--color-slider-range': '#ff9900',
        '--color-slider-thumb': '#ff9900',

        '--radius': '16px',
        '--radius-sm': '8px',
        '--radius-lg': '24px',
      },
      dark: {
        '--color-bg': '#000000',
        '--color-bg-secondary': '#1a1a2e',
        '--color-bg-card': '#0a0a1a',
        '--color-bg-hover': '#1a1a2e',
        '--color-text': '#ff9900',
        '--color-text-secondary': '#cc99cc',
        '--color-text-muted': '#9977aa',
        '--color-border': '#cc6699',
        '--color-border-hover': '#ff9900',

        '--color-sidebar-bg': '#000000',
        '--color-sidebar-text': '#cc99cc',
        '--color-sidebar-text-active': '#ff9900',
        '--color-sidebar-active-bg': '#1a1a2e',
        '--color-sidebar-hover': '#0a0a1a',

        '--color-accent': '#ff9900',
        '--color-accent-hover': '#ffaa22',
        '--color-success': '#99cc66',
        '--color-warning': '#ff9966',
        '--color-danger': '#cc6666',

        '--color-table-header': '#0a0a1a',
        '--color-table-row-hover': '#1a1a2e',
        '--color-table-stripe': '#050510',

        '--color-slider-track': '#1a1a2e',
        '--color-slider-range': '#ff9900',
        '--color-slider-thumb': '#ff9900',

        '--radius': '16px',
        '--radius-sm': '8px',
        '--radius-lg': '24px',
      },
    },
  },
];

export function getThemeById(id: string): Theme | undefined {
  return themes.find((t) => t.id === id);
}
